### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by muslih** [aimanbaharum/www.aimanbaharum.com#13]
Hi, please remove `Nobody came here to say hi :( ` :laughing:

**Comment by aimanbaharum** [comment]
@muslih HI!!!!! hahahaha I'm so flattered now i'm crying somone actually says hi here hahahahaha

Will remove the message on next version bump lol!

**Comment by muslih** [comment]
Thank you @aimanbaharum! will close this issue :laughing:
